#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <iostream>
#include <string.h>

//this cpp file is generated by copilot

// Function to encrypt the message
void caesarEncrypt(char* msg, int shift) {
    int i;
    for (i = 0; msg[i] != '\0'; i++) {
        char ch = msg[i];
        if (ch >= 'a' && ch <= 'z') {
            ch = (ch - 'a' + shift) % 26 + 'a';
        }
        else if (ch >= 'A' && ch <= 'Z') {
            ch = (ch - 'A' + shift) % 26 + 'A';
        }
        msg[i] = ch;
    }
}

// Function to decrypt the message
void caesarDecrypt(char* msg, int shift) {
    int i;
    for (i = 0; msg[i] != '\0'; i++) {
        char ch = msg[i];
        if (ch >= 'a' && ch <= 'z') {
            ch = (ch - 'a' - shift + 26) % 26 + 'a';
        }
        else if (ch >= 'A' && ch <= 'Z') {
            ch = (ch - 'A' - shift + 26) % 26 + 'A';
        }
        msg[i] = ch;
    }
}

int main() {
    char msg[100];
    int shift;

    printf("Enter a message to encrypt: ");
    fgets(msg, sizeof(msg), stdin);
    msg[strcspn(msg, "\n")] = '\0';  // Remove newline character

    printf("Enter shift value: ");
    scanf("%d", &shift);

    caesarEncrypt(msg, shift);
    printf("Encrypted message: %s\n", msg);

    caesarDecrypt(msg, shift);
    printf("Decrypted message: %s\n", msg);

    return 0;
}